#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""
==========================================================================================
PRECIPITATION RATE - RESIDUAL MLP V2
SMOTE EXPERIMENT
==========================================================================================

Purpose:
    Compare SMOTE-based training against:

        Model 1 - Baseline Residual MLP V2
        Model 2 - Random Oversampling
        Model 3 - Controlled Oversampling
        Model 4 - SMOTE

Important:
    - SMOTE is applied ONLY to the training set.
    - Validation and test sets remain completely untouched.
    - Target is GPM_precipitation_rate.
    - Model target = log1p(precipitation_rate).
    - Synthetic samples are generated by interpolation between
      minority-class training samples.
    - The precipitation target is interpolated in log1p space.
==========================================================================================
"""

import os
import random
import copy
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import TensorDataset, DataLoader

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)

# ==========================================================================================
# CONFIGURATION
# ==========================================================================================

TRAIN_FILE = "precip_positive_modis_mixed_train.csv"
VAL_FILE   = "precip_positive_modis_mixed_val.csv"
TEST_FILE  = "precip_positive_modis_mixed_test.csv"

MODEL_FILE = "precip_rate_residual_mlp_v2_smote.pt"

PREDICTION_FILE = (
    "precip_rate_residual_mlp_v2_smote_test_predictions.csv"
)

EVALUATION_FILE = (
    "precip_rate_residual_mlp_v2_smote_intensity_evaluation.csv"
)

TARGET = "GPM_precipitation_rate"

FEATURES = [
    "lat",
    "lon",
    "BT_11",
    "BT_12",
    "BTD",
    "Cloud_Mask_Binary",
    "Cloud_Mask_Raw",
    "CTT",
    "CTH",
    "Cloud_Phase",
]

# SMOTE configuration
#
# We deliberately do NOT force the extreme >20 mm/h class
# to become as large as the dominant class.
#
# Target synthetic counts are controlled here.
#
# Existing:
#   <1      = 67,274
#   1-5     = 26,781
#   5-10    =  4,071
#   10-20   =  1,281
#   >20     =    404
#
# We bring minority classes toward moderate populations.
#
SMOTE_TARGETS = {
    0: 67274,   # <1 mm/h
    1: 26781,   # 1-5 mm/h
    2: 8000,    # 5-10 mm/h
    3: 4000,    # 10-20 mm/h
    4: 1600,    # >20 mm/h
}

SMOTE_K = 5

RANDOM_SEED = 42

BATCH_SIZE = 2048
EPOCHS = 100

LEARNING_RATE = 5e-4
WEIGHT_DECAY = 1e-5

HIDDEN_DIM = 256
NUM_RESIDUAL_BLOCKS = 5
DROPOUT = 0.15

CLASSIFICATION_WEIGHT = 0.2

PATIENCE = 15

# ==========================================================================================
# REPRODUCIBILITY
# ==========================================================================================

random.seed(RANDOM_SEED)
np.random.seed(RANDOM_SEED)
torch.manual_seed(RANDOM_SEED)
torch.cuda.manual_seed_all(RANDOM_SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

# ==========================================================================================
# DEVICE
# ==========================================================================================

DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")

print("=" * 90)
print("PRECIPITATION RATE - RESIDUAL MLP V2")
print("SMOTE EXPERIMENT")
print("=" * 90)

print()
print(f"Device: {DEVICE}")

if DEVICE.type == "cuda":
    print(f"CUDA device: {torch.cuda.get_device_name(0)}")

# ==========================================================================================
# LOAD DATA
# ==========================================================================================

print()
print("=" * 90)
print("LOADING DATA")
print("=" * 90)

print()
print(f"Loading {TRAIN_FILE}...")
train_df = pd.read_csv(TRAIN_FILE)
print(f"Rows: {len(train_df):,}")
print(f"Columns: {len(train_df.columns)}")

print()
print(f"Loading {VAL_FILE}...")
val_df = pd.read_csv(VAL_FILE)
print(f"Rows: {len(val_df):,}")
print(f"Columns: {len(val_df.columns)}")

print()
print(f"Loading {TEST_FILE}...")
test_df = pd.read_csv(TEST_FILE)
print(f"Rows: {len(test_df):,}")
print(f"Columns: {len(test_df.columns)}")

# ==========================================================================================
# COLUMN VALIDATION
# ==========================================================================================

print()
print("=" * 90)
print("COLUMN VALIDATION")
print("=" * 90)

required_columns = FEATURES + [TARGET]

for name, df in [
    ("Train", train_df),
    ("Validation", val_df),
    ("Test", test_df),
]:
    missing = [c for c in required_columns if c not in df.columns]

    if missing:
        raise ValueError(
            f"{name} is missing required columns: {missing}"
        )

print("All required columns found.")

print()
print("Model input features:")

for i, feature in enumerate(FEATURES, 1):
    print(f"{i:2d}. {feature}")

print(f"\nNumber of input features: {len(FEATURES)}")

print()
print("Explicitly excluded:")
print(" - timestamp")
print(" - Cloud_Optical_Thickness")
print(" - GPM_randomError")
print(" - GPM_precipitationQualityIndex")

# ==========================================================================================
# TARGET VALIDATION
# ==========================================================================================

print()
print("=" * 90)
print("TARGET VALIDATION")
print("=" * 90)

for name, df in [
    ("Train", train_df),
    ("Validation", val_df),
    ("Test", test_df),
]:

    y = pd.to_numeric(df[TARGET], errors="coerce")

    invalid = y.isna().sum()
    zero = (y == 0).sum()
    negative = (y < 0).sum()

    print()
    print(name)
    print(f"Invalid : {invalid:,}")
    print(f"Zero    : {zero:,}")
    print(f"Negative: {negative:,}")

    if invalid > 0 or zero > 0 or negative > 0:
        raise ValueError(
            f"{name} contains invalid precipitation values."
        )

# ==========================================================================================
# MISSING VALUE HANDLING
# ==========================================================================================

print()
print("=" * 90)
print("MISSING VALUE HANDLING")
print("=" * 90)

train_medians = {}

for feature in FEATURES:

    median = train_df[feature].median()
    train_medians[feature] = median

    train_missing = train_df[feature].isna().sum()

    print(
        f"{feature:<25}"
        f"Train missing: {train_missing:7,} | "
        f"median: {median:12.6f}"
    )

    train_df[feature] = train_df[feature].fillna(median)
    val_df[feature] = val_df[feature].fillna(median)
    test_df[feature] = test_df[feature].fillna(median)

# ==========================================================================================
# TARGET TRANSFORMATION
# ==========================================================================================

print()
print("=" * 90)
print("TARGET TRANSFORMATION")
print("=" * 90)

train_y_raw = train_df[TARGET].values.astype(np.float32)
val_y_raw = val_df[TARGET].values.astype(np.float32)
test_y_raw = test_df[TARGET].values.astype(np.float32)

train_y_log = np.log1p(train_y_raw)
val_y_log = np.log1p(val_y_raw)
test_y_log = np.log1p(test_y_raw)

print()
print("Using:")
print("model target = log1p(precipitation_rate)")

print()
print(f"Raw train maximum : {train_y_raw.max():.6f}")
print(f"Log train maximum : {train_y_log.max():.6f}")

# ==========================================================================================
# FEATURE STANDARDIZATION
# ==========================================================================================

print()
print("=" * 90)
print("FEATURE STANDARDIZATION")
print("=" * 90)

X_train_raw = train_df[FEATURES].values.astype(np.float32)
X_val_raw = val_df[FEATURES].values.astype(np.float32)
X_test_raw = test_df[FEATURES].values.astype(np.float32)

feature_mean = X_train_raw.mean(axis=0)
feature_std = X_train_raw.std(axis=0)

feature_std[feature_std == 0] = 1.0

X_train = (X_train_raw - feature_mean) / feature_std
X_val = (X_val_raw - feature_mean) / feature_std
X_test = (X_test_raw - feature_mean) / feature_std

for i, feature in enumerate(FEATURES):

    print(
        f"{feature:<25}"
        f"mean={feature_mean[i]:12.6f} "
        f"std={feature_std[i]:12.6f}"
    )

# ==========================================================================================
# INTENSITY CLASSES
# ==========================================================================================

def make_intensity_class(y):

    classes = np.zeros(len(y), dtype=np.int64)

    classes[(y >= 1.0) & (y < 5.0)] = 1
    classes[(y >= 5.0) & (y < 10.0)] = 2
    classes[(y >= 10.0) & (y < 20.0)] = 3
    classes[y >= 20.0] = 4

    return classes


train_classes = make_intensity_class(train_y_raw)
val_classes = make_intensity_class(val_y_raw)
test_classes = make_intensity_class(test_y_raw)

class_names = [
    "<1 mm/h",
    "1-5 mm/h",
    "5-10 mm/h",
    "10-20 mm/h",
    ">20 mm/h",
]

print()
print("=" * 90)
print("PRECIPITATION INTENSITY CLASSES")
print("=" * 90)

print(
    f"{'':12}"
    f"{'Train':>10}"
    f"{'Val':>10}"
    f"{'Test':>10}"
)

for c, name in enumerate(class_names):

    print(
        f"{name:<12}"
        f"{(train_classes == c).sum():>10,}"
        f"{(val_classes == c).sum():>10,}"
        f"{(test_classes == c).sum():>10,}"
    )

# ==========================================================================================
# SMOTE IMPLEMENTATION
# ==========================================================================================

def smote_regression_class(
    X,
    y_log,
    classes,
    class_id,
    target_count,
    k_neighbors=5,
    random_state=42,
):
    """
    Generate synthetic samples for one intensity class.

    Feature vectors:
        x_new = x_i + lambda * (x_neighbor - x_i)

    Target:
        log_target_new =
            log_y_i + lambda * (log_y_neighbor - log_y_i)

    Thus both predictors and precipitation rate remain internally
    consistent with the interpolation.

    IMPORTANT:
        This operates only on training samples.
    """

    rng = np.random.default_rng(random_state)

    idx = np.where(classes == class_id)[0]

    current_count = len(idx)

    if target_count <= current_count:
        return (
            np.empty((0, X.shape[1]), dtype=np.float32),
            np.empty((0,), dtype=np.float32),
        )

    n_synthetic = target_count - current_count

    X_class = X[idx]
    y_class = y_log[idx]

    if current_count <= 1:
        raise ValueError(
            f"Class {class_id} has too few samples for SMOTE."
        )

    k = min(k_neighbors, current_count - 1)

    print()
    print(
        f"Class {class_id} ({class_names[class_id]}): "
        f"{current_count:,} -> {target_count:,}"
    )
    print(f"Synthetic samples: {n_synthetic:,}")
    print(f"k-neighbors     : {k}")

    # ----------------------------------------------------------------------
    # Compute nearest neighbours.
    #
    # Using numpy distance calculation in chunks avoids constructing a huge
    # N x N matrix for the full training set.
    # ----------------------------------------------------------------------

    from sklearn.neighbors import NearestNeighbors

    nn_model = NearestNeighbors(
        n_neighbors=k + 1,
        metric="euclidean",
        n_jobs=-1,
    )

    nn_model.fit(X_class)

    # Generate source indices.
    source_local = rng.integers(
        low=0,
        high=current_count,
        size=n_synthetic,
    )

    # We need nearest-neighbour candidates for the selected sources.
    selected_X = X_class[source_local]

    _, neighbor_indices = nn_model.kneighbors(selected_X)

    # First neighbour is the point itself.
    neighbor_choice = rng.integers(
        low=1,
        high=k + 1,
        size=n_synthetic,
    )

    neighbor_local = neighbor_indices[
        np.arange(n_synthetic),
        neighbor_choice,
    ]

    x1 = X_class[source_local]
    x2 = X_class[neighbor_local]

    y1 = y_class[source_local]
    y2 = y_class[neighbor_local]

    lam = rng.random(n_synthetic).astype(np.float32)

    lam_x = lam[:, None]

    X_synthetic = (
        x1 + lam_x * (x2 - x1)
    ).astype(np.float32)

    y_synthetic = (
        y1 + lam * (y2 - y1)
    ).astype(np.float32)

    return X_synthetic, y_synthetic


# ==========================================================================================
# APPLY SMOTE
# ==========================================================================================

print()
print("=" * 90)
print("SMOTE CONFIGURATION")
print("=" * 90)

print()
print("Target training counts after SMOTE:")

for c, name in enumerate(class_names):

    original = (train_classes == c).sum()
    target = SMOTE_TARGETS[c]

    synthetic = max(0, target - original)

    print(
        f"{name:<12}"
        f"Original={original:>8,} "
        f"Target={target:>8,} "
        f"Synthetic={synthetic:>8,}"
    )

print()
print("SMOTE is applied ONLY to training data.")
print("Validation and test data remain untouched.")

synthetic_X_parts = []
synthetic_y_parts = []
synthetic_class_parts = []

for c in range(5):

    X_syn, y_syn = smote_regression_class(
        X_train,
        train_y_log,
        train_classes,
        class_id=c,
        target_count=SMOTE_TARGETS[c],
        k_neighbors=SMOTE_K,
        random_state=RANDOM_SEED + c,
    )

    if len(X_syn) > 0:

        synthetic_X_parts.append(X_syn)
        synthetic_y_parts.append(y_syn)
        synthetic_class_parts.append(
            np.full(
                len(X_syn),
                c,
                dtype=np.int64
            )
        )

# Combine synthetic data.

if synthetic_X_parts:

    X_synthetic = np.concatenate(
        synthetic_X_parts,
        axis=0
    )

    y_synthetic = np.concatenate(
        synthetic_y_parts,
        axis=0
    )

    classes_synthetic = np.concatenate(
        synthetic_class_parts,
        axis=0
    )

else:

    X_synthetic = np.empty(
        (0, X_train.shape[1]),
        dtype=np.float32
    )

    y_synthetic = np.empty(
        (0,),
        dtype=np.float32
    )

    classes_synthetic = np.empty(
        (0,),
        dtype=np.int64
    )

# Combine original + synthetic.

X_train_smote = np.concatenate(
    [X_train, X_synthetic],
    axis=0
)

y_train_smote = np.concatenate(
    [train_y_log, y_synthetic],
    axis=0
)

classes_train_smote = np.concatenate(
    [train_classes, classes_synthetic],
    axis=0
)

# Shuffle the resulting training set.

rng = np.random.default_rng(RANDOM_SEED)

shuffle_idx = rng.permutation(len(X_train_smote))

X_train_smote = X_train_smote[shuffle_idx]
y_train_smote = y_train_smote[shuffle_idx]
classes_train_smote = classes_train_smote[shuffle_idx]

# ==========================================================================================
# SMOTE RESULT
# ==========================================================================================

print()
print("=" * 90)
print("SMOTE TRAINING DATA RESULT")
print("=" * 90)

print()
print(f"Original training samples : {len(X_train):,}")
print(f"Synthetic samples         : {len(X_synthetic):,}")
print(f"Final training samples    : {len(X_train_smote):,}")

print()
print("Final training class distribution:")

for c, name in enumerate(class_names):

    count = (classes_train_smote == c).sum()

    percentage = 100.0 * count / len(classes_train_smote)

    print(
        f"{name:<12}: "
        f"{count:>8,} "
        f"({percentage:6.2f}%)"
    )

# ==========================================================================================
# DATASET
# ==========================================================================================

X_train_tensor = torch.tensor(
    X_train_smote,
    dtype=torch.float32
)

y_train_tensor = torch.tensor(
    y_train_smote,
    dtype=torch.float32
)

class_train_tensor = torch.tensor(
    classes_train_smote,
    dtype=torch.long
)

X_val_tensor = torch.tensor(
    X_val,
    dtype=torch.float32
)

y_val_tensor = torch.tensor(
    val_y_log,
    dtype=torch.float32
)

class_val_tensor = torch.tensor(
    val_classes,
    dtype=torch.long
)

X_test_tensor = torch.tensor(
    X_test,
    dtype=torch.float32
)

y_test_tensor = torch.tensor(
    test_y_log,
    dtype=torch.float32
)

class_test_tensor = torch.tensor(
    test_classes,
    dtype=torch.long
)

train_dataset = TensorDataset(
    X_train_tensor,
    y_train_tensor,
    class_train_tensor
)

val_dataset = TensorDataset(
    X_val_tensor,
    y_val_tensor,
    class_val_tensor
)

test_dataset = TensorDataset(
    X_test_tensor,
    y_test_tensor,
    class_test_tensor
)

train_loader = DataLoader(
    train_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=4,
    pin_memory=True,
)

val_loader = DataLoader(
    val_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
)

test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    num_workers=4,
    pin_memory=True,
)

# ==========================================================================================
# MODEL
# ==========================================================================================

class ResidualBlock(nn.Module):

    def __init__(self, dim, dropout):

        super().__init__()

        self.fc1 = nn.Linear(dim, dim)
        self.bn1 = nn.BatchNorm1d(dim)

        self.fc2 = nn.Linear(dim, dim)
        self.bn2 = nn.BatchNorm1d(dim)

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):

        residual = x

        out = self.fc1(x)
        out = self.bn1(out)
        out = F.relu(out)
        out = self.dropout(out)

        out = self.fc2(out)
        out = self.bn2(out)

        out = out + residual
        out = F.relu(out)

        return out


class ResidualMLPV2(nn.Module):

    def __init__(
        self,
        input_dim,
        hidden_dim=256,
        num_blocks=5,
        dropout=0.15,
    ):

        super().__init__()

        self.input_layer = nn.Linear(
            input_dim,
            hidden_dim
        )

        self.input_bn = nn.BatchNorm1d(hidden_dim)

        self.blocks = nn.ModuleList([
            ResidualBlock(
                hidden_dim,
                dropout
            )
            for _ in range(num_blocks)
        ])

        self.regression_head = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 1)
        )

        self.classification_head = nn.Sequential(
            nn.Linear(hidden_dim, 128),
            nn.ReLU(),
            nn.Dropout(dropout),
            nn.Linear(128, 5)
        )

    def forward(self, x):

        x = self.input_layer(x)
        x = self.input_bn(x)
        x = F.relu(x)

        for block in self.blocks:
            x = block(x)

        regression_output = self.regression_head(x).squeeze(-1)

        classification_output = self.classification_head(x)

        return regression_output, classification_output


model = ResidualMLPV2(
    input_dim=len(FEATURES),
    hidden_dim=HIDDEN_DIM,
    num_blocks=NUM_RESIDUAL_BLOCKS,
    dropout=DROPOUT,
).to(DEVICE)

print()
print("=" * 90)
print("MODEL")
print("=" * 90)

print()
print(f"Input features : {len(FEATURES)}")
print(f"Hidden dim     : {HIDDEN_DIM}")
print(f"Residual blocks: {NUM_RESIDUAL_BLOCKS}")
print(f"Dropout        : {DROPOUT}")

parameter_count = sum(
    p.numel()
    for p in model.parameters()
)

print(f"Parameters     : {parameter_count:,}")

# ==========================================================================================
# INTENSITY WEIGHTS
# ==========================================================================================

# Keep the same regression weighting philosophy as the previous models,
# but do not introduce another sampling mechanism.
#
# These weights are applied to the regression loss only.

intensity_loss_weights = torch.tensor(
    [
        1.00,
        1.00,
        1.25,
        1.50,
        2.00,
    ],
    dtype=torch.float32,
    device=DEVICE,
)

# ==========================================================================================
# LOSS
# ==========================================================================================

def weighted_huber_loss(
    prediction,
    target,
    classes,
    delta=1.0,
):

    error = prediction - target

    abs_error = torch.abs(error)

    quadratic = torch.minimum(
        abs_error,
        torch.tensor(
            delta,
            device=prediction.device
        )
    )

    linear = abs_error - quadratic

    huber = (
        0.5 * quadratic ** 2
        + delta * linear
    )

    weights = intensity_loss_weights[classes]

    weighted = huber * weights

    return weighted.mean()


classification_loss_fn = nn.CrossEntropyLoss()

# ==========================================================================================
# OPTIMIZER / SCHEDULER
# ==========================================================================================

optimizer = torch.optim.AdamW(
    model.parameters(),
    lr=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
)

scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
    optimizer,
    mode="min",
    factor=0.5,
    patience=8,
    min_lr=1e-7,
)

# ==========================================================================================
# VALIDATION FUNCTION
# ==========================================================================================

def evaluate_loss(model, loader):

    model.eval()

    total_loss = 0.0
    total_reg = 0.0
    total_cls = 0.0
    total_samples = 0

    with torch.no_grad():

        for X_batch, y_batch, class_batch in loader:

            X_batch = X_batch.to(
                DEVICE,
                non_blocking=True
            )

            y_batch = y_batch.to(
                DEVICE,
                non_blocking=True
            )

            class_batch = class_batch.to(
                DEVICE,
                non_blocking=True
            )

            pred, class_logits = model(X_batch)

            reg_loss = weighted_huber_loss(
                pred,
                y_batch,
                class_batch
            )

            cls_loss = classification_loss_fn(
                class_logits,
                class_batch
            )

            loss = (
                reg_loss
                + CLASSIFICATION_WEIGHT * cls_loss
            )

            batch_size = len(X_batch)

            total_loss += loss.item() * batch_size
            total_reg += reg_loss.item() * batch_size
            total_cls += cls_loss.item() * batch_size

            total_samples += batch_size

    return (
        total_loss / total_samples,
        total_reg / total_samples,
        total_cls / total_samples,
    )

# ==========================================================================================
# TRAINING
# ==========================================================================================

print()
print("=" * 90)
print("TRAINING")
print("=" * 90)

print()
print("Loss:")
print(" - intensity-weighted Huber in log1p space")
print(" - auxiliary intensity classification")
print(f" - classification weight: {CLASSIFICATION_WEIGHT}")

print()
print("Sampling:")
print(" - SMOTE enabled")
print(" - synthetic samples generated ONLY from training data")

best_val_loss = float("inf")
best_epoch = 0
best_state = None

epochs_without_improvement = 0

for epoch in range(1, EPOCHS + 1):

    model.train()

    running_loss = 0.0
    running_reg = 0.0
    running_cls = 0.0
    total_samples = 0

    for X_batch, y_batch, class_batch in train_loader:

        X_batch = X_batch.to(
            DEVICE,
            non_blocking=True
        )

        y_batch = y_batch.to(
            DEVICE,
            non_blocking=True
        )

        class_batch = class_batch.to(
            DEVICE,
            non_blocking=True
        )

        optimizer.zero_grad(set_to_none=True)

        pred, class_logits = model(X_batch)

        reg_loss = weighted_huber_loss(
            pred,
            y_batch,
            class_batch
        )

        cls_loss = classification_loss_fn(
            class_logits,
            class_batch
        )

        loss = (
            reg_loss
            + CLASSIFICATION_WEIGHT * cls_loss
        )

        loss.backward()

        torch.nn.utils.clip_grad_norm_(
            model.parameters(),
            max_norm=5.0
        )

        optimizer.step()

        batch_size = len(X_batch)

        running_loss += loss.item() * batch_size
        running_reg += reg_loss.item() * batch_size
        running_cls += cls_loss.item() * batch_size

        total_samples += batch_size

    train_loss = running_loss / total_samples
    train_reg = running_reg / total_samples
    train_cls = running_cls / total_samples

    val_loss, val_reg, val_cls = evaluate_loss(
        model,
        val_loader
    )

    scheduler.step(val_loss)

    current_lr = optimizer.param_groups[0]["lr"]

    print(
        f"Epoch {epoch:03d}/{EPOCHS} | "
        f"Train: {train_loss:.6f} | "
        f"Val: {val_loss:.6f} | "
        f"Reg: {val_reg:.6f} | "
        f"Cls: {val_cls:.6f} | "
        f"LR: {current_lr:.2e}"
    )

    if val_loss < best_val_loss:

        best_val_loss = val_loss
        best_epoch = epoch

        best_state = copy.deepcopy(
            model.state_dict()
        )

        torch.save(
            {
                "model_state_dict": best_state,
                "feature_mean": feature_mean,
                "feature_std": feature_std,
                "features": FEATURES,
                "target": TARGET,
                "best_epoch": best_epoch,
                "best_val_loss": best_val_loss,
                "smote_targets": SMOTE_TARGETS,
                "smote_k": SMOTE_K,
            },
            MODEL_FILE
        )

        epochs_without_improvement = 0

        print(
            f" -> Saved best model: {MODEL_FILE}"
        )

    else:

        epochs_without_improvement += 1

    if epochs_without_improvement >= PATIENCE:

        print()
        print("Early stopping.")
        break

# ==========================================================================================
# LOAD BEST MODEL
# ==========================================================================================

print()
print("=" * 90)
print("LOADING BEST MODEL")
print("=" * 90)

checkpoint = torch.load(
    MODEL_FILE,
    map_location=DEVICE
)

model.load_state_dict(
    checkpoint["model_state_dict"]
)

print()
print(f"Best epoch     : {best_epoch}")
print(f"Best val loss  : {best_val_loss:.6f}")

# ==========================================================================================
# TEST PREDICTIONS
# ==========================================================================================

print()
print("=" * 90)
print("GENERATING TEST PREDICTIONS")
print("=" * 90)

model.eval()

pred_log_list = []
actual_log_list = []
class_list = []

with torch.no_grad():

    for X_batch, y_batch, class_batch in test_loader:

        X_batch = X_batch.to(
            DEVICE,
            non_blocking=True
        )

        pred, _ = model(X_batch)

        pred_log_list.append(
            pred.cpu().numpy()
        )

        actual_log_list.append(
            y_batch.numpy()
        )

        class_list.append(
            class_batch.numpy()
        )

pred_log = np.concatenate(pred_log_list)
actual_log = np.concatenate(actual_log_list)
test_classes_eval = np.concatenate(class_list)

# Back-transform.

pred_raw = np.expm1(pred_log)
actual_raw = np.expm1(actual_log)

# Physical constraint.

pred_raw = np.maximum(
    pred_raw,
    0.0
)

# ==========================================================================================
# OVERALL METRICS
# ==========================================================================================

mae = mean_absolute_error(
    actual_raw,
    pred_raw
)

rmse = np.sqrt(
    mean_squared_error(
        actual_raw,
        pred_raw
    )
)

r2 = r2_score(
    actual_raw,
    pred_raw
)

correlation = np.corrcoef(
    actual_raw,
    pred_raw
)[0, 1]

bias = np.mean(
    pred_raw - actual_raw
)

print()
print("=" * 90)
print("RESIDUAL MLP V2 SMOTE TEST RESULTS")
print("=" * 90)

print()
print("Positive precipitation samples only.")

print()
print(f"Samples     : {len(actual_raw):,}")
print(f"MAE         : {mae:.6f}")
print(f"RMSE        : {rmse:.6f}")
print(f"R²          : {r2:.6f}")
print(f"Correlation : {correlation:.6f}")
print(f"Bias        : {bias:.6f}")

# ==========================================================================================
# INTENSITY PERFORMANCE
# ==========================================================================================

print()
print("=" * 90)
print("PRECIPITATION INTENSITY PERFORMANCE")
print("=" * 90)

print(
    f"{'Range':<18}"
    f"{'N':>8}"
    f"{'Actual':>12}"
    f"{'Pred':>12}"
    f"{'MAE':>12}"
    f"{'RMSE':>12}"
    f"{'R2':>12}"
    f"{'Bias':>12}"
)

print("-" * 100)

evaluation_rows = []

for c, name in enumerate(class_names):

    mask = test_classes_eval == c

    actual_c = actual_raw[mask]
    pred_c = pred_raw[mask]

    mae_c = mean_absolute_error(
        actual_c,
        pred_c
    )

    rmse_c = np.sqrt(
        mean_squared_error(
            actual_c,
            pred_c
        )
    )

    r2_c = r2_score(
        actual_c,
        pred_c
    )

    bias_c = np.mean(
        pred_c - actual_c
    )

    print(
        f"{name:<18}"
        f"{len(actual_c):>8,}"
        f"{actual_c.mean():>12.4f}"
        f"{pred_c.mean():>12.4f}"
        f"{mae_c:>12.4f}"
        f"{rmse_c:>12.4f}"
        f"{r2_c:>12.4f}"
        f"{bias_c:>12.4f}"
    )

    evaluation_rows.append({
        "range": name,
        "N": len(actual_c),
        "Actual": actual_c.mean(),
        "Pred": pred_c.mean(),
        "MAE": mae_c,
        "RMSE": rmse_c,
        "R2": r2_c,
        "Bias": bias_c,
    })

# ==========================================================================================
# EXTREME PERFORMANCE
# ==========================================================================================

print()
print("=" * 90)
print("EXTREME PRECIPITATION PERFORMANCE")
print("=" * 90)

thresholds = [1, 5, 10, 20]

for threshold in thresholds:

    mask = actual_raw >= threshold

    actual_e = actual_raw[mask]
    pred_e = pred_raw[mask]

    mae_e = mean_absolute_error(
        actual_e,
        pred_e
    )

    rmse_e = np.sqrt(
        mean_squared_error(
            actual_e,
            pred_e
        )
    )

    r2_e = r2_score(
        actual_e,
        pred_e
    )

    bias_e = np.mean(
        pred_e - actual_e
    )

    print()
    print(
        f"Actual rate >= {threshold} mm/h"
    )

    print(
        f"Samples       : {len(actual_e):,}"
    )

    print(
        f"Actual mean   : {actual_e.mean():.4f}"
    )

    print(
        f"Predicted mean: {pred_e.mean():.4f}"
    )

    print(
        f"MAE           : {mae_e:.4f}"
    )

    print(
        f"RMSE          : {rmse_e:.4f}"
    )

    print(
        f"R²            : {r2_e:.4f}"
    )

    print(
        f"Bias          : {bias_e:.4f}"
    )

# ==========================================================================================
# MAXIMUM VALUES
# ==========================================================================================

print()
print("=" * 90)
print("MAXIMUM VALUES")
print("=" * 90)

print()
print(f"Actual maximum    : {actual_raw.max():.6f}")
print(f"Predicted maximum : {pred_raw.max():.6f}")

top_indices = np.argsort(
    actual_raw
)[::-1][:20]

print()
print("Top 20 actual precipitation cases:")
print()
print(
    f"{'Actual':>14}"
    f"{'Predicted':>14}"
    f"{'Error':>14}"
)

print("-" * 45)

for idx in top_indices:

    actual_value = actual_raw[idx]
    pred_value = pred_raw[idx]
    error = pred_value - actual_value

    print(
        f"{actual_value:14.6f}"
        f"{pred_value:14.6f}"
        f"{error:14.6f}"
    )

# ==========================================================================================
# SAVE PREDICTIONS
# ==========================================================================================

print()
print("=" * 90)
print("SAVING PREDICTIONS")
print("=" * 90)

prediction_df = test_df.copy()

prediction_df["actual_precipitation_rate"] = actual_raw
prediction_df["predicted_precipitation_rate"] = pred_raw
prediction_df["prediction_error"] = (
    pred_raw - actual_raw
)

prediction_df.to_csv(
    PREDICTION_FILE,
    index=False
)

print()
print("Saved predictions:")
print(
    f"  {PREDICTION_FILE}"
)

# ==========================================================================================
# SAVE EVALUATION
# ==========================================================================================

evaluation_df = pd.DataFrame(
    evaluation_rows
)

evaluation_df.to_csv(
    EVALUATION_FILE,
    index=False
)

print()
print("Saved evaluation:")
print(
    f"  {EVALUATION_FILE}"
)

# ==========================================================================================
# FINAL SUMMARY
# ==========================================================================================

print()
print("=" * 90)
print("FINAL SUMMARY")
print("=" * 90)

print()
print(f"Best validation loss : {best_val_loss:.6f}")
print(f"Best epoch           : {best_epoch}")

print()
print(f"Test MAE             : {mae:.6f}")
print(f"Test RMSE            : {rmse:.6f}")
print(f"Test R²              : {r2:.6f}")
print(f"Test correlation     : {correlation:.6f}")
print(f"Test bias            : {bias:.6f}")

print()
print("SMOTE target counts:")

for c, name in enumerate(class_names):

    print(
        f"  {name:<12}: "
        f"{SMOTE_TARGETS[c]:,}"
    )

print()
print(f"SMOTE k-neighbors : {SMOTE_K}")

print()
print("Model:")
print(
    f"  {MODEL_FILE}"
)

print()
print("Predictions:")
print(
    f"  {PREDICTION_FILE}"
)

print()
print("Evaluation:")
print(
    f"  {EVALUATION_FILE}"
)

print()
print("=" * 90)
print("DONE")
print("=" * 90)
